"""
This file contains the locators for the 'Email' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
EmailMenu = "xpath=//*[text()='Email']"
Email_breadcrums = "xpath=//li//span[text()='Emails']"
CreateNewMessageButton = "xpath=//a[text()='Create New Message']"
NewEmailButton = "xpath=//a[text()='New']"
NewMessageTitle = "xpath=//*[text()='New Message']"
FromField = "xpath=//input[@name='from']"
RecipientsField = "xpath=(//label[text()='To:']//following::input)[1]"
SubjectField = "xpath=//input[@name='subject']"
EmailBody = "xpath=//p[contains(@data-placeholder,'Type your message here')]"
SubmissionAssetsButton = "xpath=//button[text()='Submission Assets']"
SubmissionAssetsDialog = "xpath=//p[text()='Select one or more assets to attach to your message.']"
SelectOriginalDocument = "xpath=//label[.//div[text()='"
SelectOriginalDocument_checkbox = "']]//preceding-sibling::*[@role='checkbox']"
Attach1AssetButton = "xpath=//div[@role='dialog']//button[text()='Attach' and '1 asset']"
AttachmentText = "xpath=//ul[@id='attachments']//a"
SendButton = "xpath=//button//div[text()='Send']"
EmailSentSuccessfully = "xpath=//*[contains(text(),'Email sent successfully')]"
SentEmailCard = "xpath=(//aside//a)[1]"
EmailCard = "//*//span[text()='"
SentEmailContent = "xpath=(//main)[2]//*[text()='"
AttachmentText_MultipleValues = "xpath=(//ul[@id='attachments']//a)["
Missing_PopUp_Loc="//p[text()='"
Save_Draft="(//button[text()='Save Draft'])[1]"
Draft_mail_Loc="((//aside//a)//span[text()='Draft'])[1]"
Resiver_Mail="(//label[text()='To:']//following-sibling::div//span/span)[1]"
Body_Msg="(//div[@data-slot='form-item'])[4]//p"
Draft_Saved_Msg="//div[text()='Email draft saved.']"
Discard_Button="//button[text()='Discard']"