"""
This file contains the locators for the 'Forms' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
 
FormsMenu = "xpath=//*[text()='Forms']"
RegenerateButton = "xpath=//button[text()='Regenerate']"
FormsPage = "xpath=//form//*[text()='Forms']"
FormSummaryHeader = "xpath=(//section[@id='summary-aside-header'])[1]"#New
FormSummaryDetails = "xpath=//section[@id='summary-aside-details']//span"
FormSummaryDetail = "xpath=(//section[@id='summary-aside-details']//span)[1]"
FormsPIFOption = "xpath=//section[@id='forms-aside-forms']//span[text()='Policy Instruction Form']"
PIFGeneralData = "xpath=//section[@id='pif-general']//preceding-sibling::label[not(contains(text(),'Needed By Date'))]//following-sibling::button"
PIFProducerData = "xpath=//section[@id='pif-producer']//input"
PIFInsuredData = "xpath=//section[@id='pif-insured-information']//label//following-sibling::*"
PIFProcessingdData = "xpath=//section[@id='pif-processing-information']//button//span//ancestor::div[1][text()]"
PIFPolicyInputField = "xpath=//label[text()='Policy Number']//following-sibling::input"
PIFNeededByDateField = "xpath=//label[text()='Needed By Date']//following-sibling::button"
PIFGeneralDateSelect = "xpath=//td//button[not(contains(@class,'day-outside')) and text()='"
PIFInsuredYearEstablished = "xpath=//label[text()='Year Established']//following-sibling::input"
PIFInsuredOperationDesc = "xpath=//label[text()='Description of Operations']//following-sibling::textarea"
PIFInsuredYearsInBusiness = "xpath=//label[text()='Years in Business']//following-sibling::input"
PIFInsuredRevenueEstimate = "xpath=//label[text()='Revenue Estimate']//following-sibling::input"
PIFInsuredDomiciledState = "xpath=//label[text()='Exposure Outside Domiciled State']//following-sibling::textarea"
PIFInsuredOutSideTheUS = "xpath=//label[text()='Exposure Outside the U.S.']//following-sibling::textarea"
PIFProcessingExpected = "xpath=//section[@id='pif-processing-information']//button//div[1]//div"
PIFProcessingUWOffice = "xpath=//label[text()='UW Office']//following-sibling::button"
PIFProcessingUWOfficeOption = "xpath=//span[text()='"
PIFProcessingRepOffice = "xpath=//label[text()='Rep Office']//following-sibling::button"
PIFProcessingChannel = "xpath=//label[text()='Channel']//following-sibling::button"
PIFProcessingSubChannel = "xpath=//label[text()='Sub Channel']//following-sibling::button"
PIFUWWrittingCompany = "xpath=//label[text()='Writing Company']//following-sibling::button"
PIFUWRadioButton1 = "xpath=//label[text()='"
PIFUWRadioButton2 = "']//preceding-sibling::button"#New
PIFHGSICCode = "xpath=//label[text()='SIC Code']//following-sibling::input"
PIFHGNAICSCode = "xpath=//label[text()='NAICS Code']//following-sibling::input"
# PIFHGProperty = "xpath=//label[text()='Property']//following-sibling::input"
PIFHGProperty = "xpath=//label[text()='General Prod']//following-sibling::input"
# PIFHGPropertyNetCompanyLimit = "xpath=//label[text()='Property Net Company Limit']//following-sibling::input"
PIFHGPropertyNetCompanyLimit = "xpath=//label[text()='GL Prem']//following-sibling::input"
PIFReinsuranceCdedPrescentage = "//label[text()='Ceded Reinsurance %']//following-sibling::div//input"
PIFInstructionDate = "xpath=//label[text()='Date']//following-sibling::button"
PIFInstructionsAdditionalInformation = "xpath=//label[text()='Additional Information']//following-sibling::textarea"
Loc_PIF_NeededDate = "xpath=//label[text()='Needed By Date']//following-sibling::button"
Loc_PIF_InsuredDetails1 = "xpath=//label[text()='"
Loc_PIF_InsuredDetails2 = "']//following-sibling::input"
Loc_PIF_Process_Detail1 = "xpath=//label[text()='"
Loc_PIF_Process_Detail2 = "']//following-sibling::button"
Loc_Writing_Company = "xpath=//label[text()='Writing Company']//following-sibling::button"
#NY Free Trade Zone Form
FormsNYFTZOption = "xpath=//section[@id='forms-aside-forms']//span[text()='NY Free Trade Zone']"
NYFExpectedInstructions = "xpath=//section[@id='nyftz-instructions']//li//div"
NYFDocumentationUnderwriter = "xpath=(//label[text()='Underwriter']//following-sibling::button//div)[1]"
NYFDocumentationPolicyNumber = "xpath=//label[text()='Policy Number']//following-sibling::input"
NYFDocumentationPolicyPremiumField = "xpath=//label[text()='Policy Premium']//following-sibling::div//input"
NYFDocumentationNYPremiumField = "xpath=//label[text()='NY Premium']//following-sibling::div//input"
NYFEligibilityClass1Field = "xpath=//label[text()='Class 1']//following-sibling::textarea"
NYFEligibilityClass2Field = "xpath=//label[text()='Class 2']//following-sibling::textarea"
NYFEligibilityClass3Field = "xpath=//label[text()='Class 3']//following-sibling::textarea"
NYFExposuresClassificationField = "xpath=//label[text()='Classification (ISO)']//following-sibling::input"
NYFExposuresDescriptionField = "xpath=//label[text()='Description (ISO)']//following-sibling::input"
NYFExposuresLimitsProvidedField = "xpath=//label[text()='Limits Provided']//following-sibling::input"
NYFUnderwritingEvaluationField = "xpath=//label[text()='Evaluation']//following-sibling::textarea"
 
#Rate Form
RateForm = "xpath=//span[text()='Rate Form']"
RateFormHeader = "xpath=//h1[text()='Rate Form']"
ReasonForDocumentation = "id=reason-for-documentation"
ReasonForDocumentationOption  = "//button[@role='radio' and @value='"
ReasonForDocumentationText = "xpath=//section[@id='reason-for-documentation']/div[1]/div"
GeneralSection = "id=rating-general"
GeneralSectionText = "xpath=//section[@id='rating-general']/div[1]/div"
PolicyNumber = "xpath=//label[text()='Policy Number']//following-sibling::input"
PolicyEffectiveDate = "xpath=//label[text()='Effective Date']//following-sibling::button/div"
WritingCompanyDropdown = "xpath=//label[text()='Writing Company']//following-sibling::select"
DeviatedRateLocationText = "xpath=(//section[@id='rating-locations']/div[1])/div"
AddButtonInDeviatedRateLocations = "xpath=//button[text()='Add Location']"
AddDeviatedLocationDialogBox = "xpath=//h2[text()='Add Deviated Rate Locations']"
SelectLocation = "xpath=//button[@role='checkbox'][..//label[text()='"
CloseDialogBox = "xpath=//span[text()='Close']"
DeviatedRateCoverage = "xpath=//section[@id='rating-coverage']/div[1]/div"
SelectAllApplicableCoverages = "xpath=//button[@role='checkbox'][..//label[text()='"
Limits = "xpath=//label[text()='Limits']//following-sibling::input"
Classification = "xpath=//label[text()='Classification']//following-sibling::input"
Code = "xpath=//label[text()='Code']//following-sibling::input"
ExposureBasis = "xpath=//label[text()='Exposure Basis']//following-sibling::input"
RatingDetailText = "xpath=//section[@id='rating-form-detail']/div[1]/div"
ManualFactorPremisesValuePrefix = "xpath=(//tr[(.//td[text()='"
ManualFactorPremissesSuffix = "'])])[1]/td//input[contains(@name,'premises')]"
ManualFactorProductsValuePrefix = "xpath=(//tr[(.//td[text()='"
ManualFactorProductsSuffix = "'])])[1]/td//input[contains(@name,'products')]"
SelectedFactorPremisesValuePrefix = "xpath=//th[text()='Selected Factor(s)']//following::tbody//tr[.//td[text()='"
SelectedFactorPremisesValueSuffix = "']]//input[contains(@name,'premises')]"
SelectedFactorProductsValuePrefix = "xpath=//th[text()='Selected Factor(s)']//following::tbody//tr[.//td[text()='"
SelectedFactorProductsSuffix = "']]//input[contains(@name,'products')]"
DeviatedRateEligibility = "xpath=//label[text()='Deviated Rate Eligibility Criteria']//following-sibling::textarea"
DeviatedRateExposure = "xpath=//label[text()='Deviated Rate Exposure Description']//following-sibling::textarea"
DeviatedRateExposureDescription = "xpath=//label[text()='Deviated Rate Exposure Description']//following-sibling::p"
DeviatedRateEligibilityDescription = "xpath=//label[text()='Deviated Rate Eligibility Criteria']//following-sibling::p"
AttachedDocumentName  = "xpath=//span[text()='"
SaveChangesButton = "xpath=//button[text()='Save Changes']"
SaveChangesPopup = "xpath=(//section[@aria-label='Notifications alt+T']//div[@data-title and text()='"#New
Loc_DerivedLocation = "xpath=//div[text()='" 
Loc_DeviatedRate = "xpath=//button//preceding-sibling::div[text()='"#New
Loc_Upload_cancel_Btn = "xpath=(//span[text()='"#New
Loc_Upload_cancel_Btn1 = "']//following::button)[1]"#New
#In Forms Manuscript Tab
Loc_Manuscript_btn = "xpath=//span[text()='Manuscript']"
Loc_Manuscript_Tab_Verify = "xpath=//h1[text()='Manuscript']"
Loc_Reason_Tab_verify = "xpath=//div[text()='Reason for Documentation']"
Loc_Deregulation_Checkbox="xpath=//label[text()='Deregulation']"
Loc_Manuscript_Form_Checkbox="xpath=//label[text()='Manuscript Forms']"
#General
Loc_General_Tab = "xpath=//div[text()='General']"
Loc_WritingCom_Verify = "xpath=//label[text()='Writing Company']//following-sibling::button"
Loc_PolicyNo = "xpath=//label[text()='Policy Number']//following-sibling::input"
Loc_EffecDate = "xpath=//label[text()='Effective Date']//following-sibling::button"
Loc_ExpiryDate = "xpath=//label[text()='Expiration Date']//following-sibling::button"
 
#Refer to Lines of Business
Loc_Refer_Lines = "xpath=//div[text()='Refer to Lines of Business']"
Loc_ReferLines_Checkbox1 = "xpath=//label[text()='"
Loc_ReferLines_Checkbox2 = "']//preceding-sibling::button"
 
#Insured Information
Loc_SelectState = "xpath=//label[text()='State where Manuscript(s) apply']//following-sibling::select"
Loc_State_Select = "xpath=//option[text()='"
 
#ManuScript Details
Loc_Description = "xpath=//p[text()='Attach draft/sample.']//following-sibling::textarea"
Loc_Desc_Explore = "xpath=//p[text()='Include specific Supporting Reason(s) for Chosen Rate(s).']//following-sibling::textarea"
Loc_Attachment_Select = "xpath=//section[@id='manuscript-attachments']//following::span[text()='"
 
#Company Underwriting Eligibility Guidelines
FormsCUEGOption = "xpath=//section[@id='forms-aside-forms']//span[text()='Company Underwriting Eligibility Guidelines']"
CUEGExpectedGeneralEffectiveDate = "xpath=//label[text()='Effective Date']//following-sibling::button//div"
CUEGTotalPointsField = "xpath=//label[text()='Total Points']//following-sibling::input"
CUEGTotalPointsTableHeaders = "xpath=//section[@id='eligibility-total-point-range']//table//th"
CUEGTotalPointsTableData = "xpath=//section[@id='eligibility-total-point-range']//table//td"
CUEGManagementDetails = "xpath=//section[@id='eligibility-management-attitude']//div//li"
CUEGCompanyInspectionDetails = "xpath=//section[@id='eligibility-company-inspection']//div//li"
CUEGCompanyInventoryRecords = "xpath=//label[text()='Inventory records']//following-sibling::textarea"
 
#Reinsurance Form
FormsReinsuranceOption = "xpath=//section[@id='forms-aside-forms']//span[text()='Reinsurance']"
ReinsuranceFacultativeObligatory = "xpath=//label[text()='Facultative Obligatory']//p"
ReinsuranceFacultativeReinsurance = "xpath=//label[text()='Facultative Reinsurance']//div"
ReinsuranceEquipmentBreakdown = "xpath=//label[text()='Equipment Breakdown']//div"
ReinsuranceAssumedReinsurance = "xpath=//label[text()='Assumed Reinsurance']//p"
ReinsuranceSwiftRe = "xpath=//label[text()='Swift Re']//p"
ReinsuranceCheckBoxes1 = "xpath=//label[text()='"
ReinsuranceCheckBoxes2 = "']/..//preceding-sibling::button"
ReinsuranceCheckBoxes3 = "']/..//preceding-sibling::input"

ReinsuranceCheckBoxes = "xpath=//label/..//preceding-sibling::button"
ReinsuranceCheckBoxStatus = "xpath=//label/..//preceding-sibling::input"

#NY Underwriting Eligibility Guidelines Form
FormsNYUEGOption = "xpath=//section[@id='forms-aside-forms']//span[text()='NY Underwriting Eligibility Guidelines']"
FormsNYUEGPremiumDocumentation = "xpath=//label[text()='Documentation']//following-sibling::textarea"
NYUEGTotalPointsField = "xpath=//label[text()='Total Point Range']//following-sibling::input"
NYUEGTotalPointsTableHeaders = "xpath=//section[@id='ny-eligibility-total-point-range']//table//th"
NYUEGTotalPointsTableData = "xpath=//section[@id='ny-eligibility-total-point-range']//table//td"

#Complete Form
Loc_CompleteForm_btn = "xpath=//section[@id='policy-form-footer']//button"