ReferralButton= "xpath=//button//*[text()='Referral']"
ReferSubmission = "xpath=//h2[text()='Refer Submission']"
ReferralReasonsDropdown = "xpath=//select[@ng-click='$ctrl.toggleReferralReasonsDropdown()']"
ReferralDropdownMenu = "id=reasons-dropdown-menu"
ReferUserDropdown= "xpath=//button[@ng-click='$ctrl.referralClickUserChevron()']"
ReferToUser = "xpath=//li//span[text()='"
ReferDetails = "xpath=//textarea[@ng-model='$ctrl.referralDetails']"
ReferButton = "xpath=//button//*[text()='Refer']"
ReferredDetails = "xpath=//div[@ng-repeat='referral in $ctrl.referrals']"
RferralPending= "xpath=//button//*[text()='Referral Pending']"
ReferralReason1 = "xpath=//span[text()='"
ReferralReason2 = "']//preceding-sibling::input"
ReferUserField = "xpath=(//p[text()='Refer to user']//following::input)[1]"