"""
This file contains the locators for the main 'Summary' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
SummaryTab_loc  ="xpath=//a[@title='Summary']"
Sum_Header_loc  ="xpath=//section[@id='summary-header']"
premium_loc    ="xpath=//input[@data-slot='input']"
permium_Btn_Loc ="xpath=//div[text()='Premium']/following-sibling::div//button"
policy_Btn_Loc = "xpath=//div[text()='Policy Number']/following-sibling::div//button"
Attachement_point_btn_loc ="xpath=//div[text()='Attachment Point']/following-sibling::div//button"
policy_field_Loc ="xpath=//div[text()='Policy Number']/following-sibling::div//input"
premium_field_loc   ="xpath=//div[text()='Premium']/following-sibling::div//input"
Attachement_point_field_loc   ="xpath=//div[text()='Attachment Point']/following-sibling::div//input"
Sum_Address_loc  ="xpath=//section[@id='summary-aside-header']//p//span"
Loc_AllField = "xpath=//ui-view[@name='submission-sidebar']//li//ul//span[@ng-show]"
page_header_Loc   ="xpath=//span[@data-slot='breadcrumb-page']"
Loc_Header_Status  = "xpath=//span[@data-slot='dropdown-menu-trigger']"
Headers_Loc  = "xpath=//a[@data-slot='breadcrumb-link']"
loc_ClassOf_Business="//div[text()='Class of Business']/following-sibling::div//button"
Loc_Placement_Button="//div[text()='Policy Placement Type']/following-sibling::div//button"

loc1_Select_Type="//div[@data-slot='select-item']//span[text()='"
PolicyDataModification = "xpath=(//a[normalize-space()='Policy Data Modification'])[2]"
policy_locators1 = "xpath =//*[@class='ace_line'][.//span[contains(text(),'"     
policy_locators2 ="')]]/span[contains(@class,'ace_string') or contains(@class,'ace_numeric')]"
Search_Bar_CtrlF="xpath=//input[@placeholder='Search for']"
poloicy_Data_modification_page="xpath=//div[@class=' ace_editor ace-jsoneditor']"

permium_Field ="xpath=//div[text()='Premium']"
policy_Field = "xpath=//div[text()='Policy Number']"
Attachement_point_Field ="xpath=//div[text()='Attachment Point']"

loc_ClassOf_Business_Field="//div[text()='Class of Business']"
Loc_Placement_Field="//div[text()='Policy Placement Type']"
loc_Mailed_Date_Field="//div[text()='Mailed Date']"
Expected_Status_Type_Loc="(//tbody/tr//a[text()='Wholesale Team']/..//following-sibling::td[1])[1]"
Expected_Product_Type_Loc="(//tbody/tr//a[text()='Wholesale Team'])[1]"
Expected_Eff_date_loc="(//tbody/tr//a[text()='Wholesale Team']/..//following-sibling::td[2])[1]"
Expected_Exp_date_loc="(//tbody/tr//a[text()='Wholesale Team']/..//following-sibling::td[3])[1]"
Loc_current_text1="//a[text()='"
Loc_current_text2="']//span[@data-slot='badge']"
Convr_Home_Btn="//div[@data-slot='sidebar-header']"
Workflow_Lists="//submission-sidebar-workflow//li"
Summary_Workflow_Lists="//div[@data-slot='dropdown-menu-content']//div[@role='menuitem']"

#New[201Bugs]
Summary_Workflow_Stages = "xpath=//*[text()='Workflow']//following-sibling::div//*[contains(@class,'text-tiny! font-medium')]"
Summary_Stage_Processing = "xpath=//div[contains(@class,'border-muted-foreground')]//span[text()]"
Summary_Stage_completed = "xpath=//div[contains(@class,'border-muted-foreground')]//span"
Summary_Stage_Dropdown = "xpath=//span[@data-slot='dropdown-menu-trigger']"
Summary_Adv_Stage = "xpath=(//div[@data-slot='dropdown-menu-item'])[1]"


