"""
This file contains the locators for the 'Tasks' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
SearchTask = "id:search-tasks"
TableHeader = "xpath=//th"
Tasks = "//a[normalize-space()='Tasks']"
SchemaButton =  "//button//*[text()='Schema']"
TasksMenu = "//a[@test-id='tasknav']"
NoTasks = "//*[text()='No Tasks']"
CreateNewTaskButton = "//button//*[text()='Create a Task']"
NewTaskButton = "//button//*[text()='New Task']"
CreateTaskTab = "//h2[@test-id='create-edit-task-header']"
TaskNameDropdown = "//select[@name='task-template']"
CustomTaskName = "//input[@name='task-name']"
TaskRequiredCheckBox = "id=reason-required"
AssignTo  = "//label[text()='Assign To ']//following::*[@test-id='assigned-to-non-editable']"
SelectAssignee = "//div[text()='Select one person']//following::span[text()='"
DueDate =  "//input[@test-id='due-date-inp-calendar']"
PriorityDropdown = "//select[@test-id='task-priority-select']"
TaskDetails = "//*[@test-id='task-details-text']"
TaskReason = "//*[@test-id='task-completion-reason']"
TaskData1 = "//tr[td[normalize-space()='"
TaskData2 = "'] and td[normalize-space()='"
CreateButton = "//button//span[normalize-space()='Create']"
TaskCreatedPopup = "//*[contains(text(),'Task created')]"
Home = "//li//a[normalize-space()='Home']"
TaskNameInTable = "//td[normalize-space()='"
TaskIDFromTable1 = "//td[normalize-space()='"
TaskIDFromTable2="']/ancestor::tr/td[contains(@ng-show,'taskId')]"
FinalTableData = "(//*[normalize-space()='"
FinalTaskName = "//td[normalize-space()='"
TaskDetailHeader = "//task-detail-header//h2"
TaskCard1 = "//div[normalize-space()='"
TaskCard2 = "' and @test-id='task-left-menu']"
TaskHeader = "xpath=//task-detail-header//h2"
Task_edit = "xpath=//d3-button[@test-id='task-edit']"
Task_delete = "xpath=//d3-button[@test-id='task-delete-options']"
Complete_Task = "xpath=//d3-button[@test-id='task-completed']"
Save_edited_task="xpath=//d3-button[@test-id='create-task-btn']"
Task_updated_popup = "xpath=//div[text()='Task updated']"
Get_delpopup = "xpath=//p[text()='Are you sure you want to delete this task?']"
Del_Task_button = "xpath=//d3-button[@test-id='task-deletetask-modal-options']"
Cancel_del = "xpath=//d3-button[@test-id='task-canceltask-modal-options']"
Task_del_popup="xpath=//div[text()='Task deleted']"
Task_Name_Loc="//h2[text()='"
Task_Find_Locator="xpath=//div[@test-id='task-left-menu' and normalize-space()='"
Task_completed = "xpath=(//div[@test-id='test-complete-label'] //following::div)[1]"
TaskClick = "xpath=(//a[@test-id='tasknav']//following-sibling::span)[1]"